apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
  name: vals-secret-virtualisation-technical-user
  labels:
    owner: digitalis.io
spec:
  name: vmware-secret # Optional, default is the resource name
  ttl: 3600       # Optional, default is 0. The secret will be checked at every "reconcile period". See below.
  type: Opaque    # Default type, others supported
  data:
    USERNAME:
      ref: ref+vault://secret/<username>
      encoding: text
    PASSWORD:
      ref: ref+vault://secret/<password>
      encoding: text
---
apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
  name: vals-secret-proxy
  labels:
    owner: digitalis.io
spec:
  name: proxy-secret # Optional, default is the resource name
  ttl: 3600       # Optional, default is 0. The secret will be checked at every "reconcile period". See below.
  type: Opaque    # Default type, others supported
  data:
    PROXY-URL:
      ref: ref+vault://secret/<url>
      encoding: text
    PROXY-USER:
      ref: ref+vault://secret/<user>
      encoding: text
    PROXY-PASSWORD:
      ref: ref+vault://secret/<password>
      encoding: text
    NO-PROXY:
      ref: ref+vault://secret/<no_proxy>
      encoding: text
